name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver to tag (must match package.json on main)'
        required: true
        type: string
      prerelease:
        description: 'Mark the GitHub Release as a prerelease?'
        required: false
        default: 'false'
        type: choice
        options: ['false', 'true']

permissions:
  contents: write

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Sanity checks
        run: |
          git fetch --tags --force
          VERSION="${{ inputs.version }}"
          if git rev-parse "v$VERSION" >/dev/null 2>&1; then
            echo "Tag v$VERSION already exists"; exit 1
          fi
          PKG_VERSION=$(node -e "console.log(require('./package.json').version)")
          if [ "$PKG_VERSION" != "$VERSION" ]; then
            echo "package.json version ($PKG_VERSION) != input ($VERSION)"; exit 1
          fi

      - name: Create and push tag
        run: |
          VERSION="${{ inputs.version }}"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"

      - name: Create GitHub Release (auto notes)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ inputs.version }}" \
            --generate-notes \
            $([ "${{ inputs.prerelease }}" = "true" ] && echo --prerelease || true)
